# SITE CONFIGURATION
title: LaSchool Blogs # your site title
author: LaTecSo Admin # You :P
description: > # Meta description of Homepage
  LaTecSo aims at addressing the challenges faced by legal sector by providing multiple technology-based solutions. The products being developed by LaTecSo addresses the day-to-day challenges faced by the stakeholder in legal sector. LaTecSo aims at solving technological problems faced by a wide range of stakeholders including Law Firms, Law Students, Legal Practitioners, Customers of Legal Services, Legal Authorities, etc. Right from solving the basic issues like filling the communication gap to solving complex issues like dispute resolution, LaTecSo empowers legal sector and makes access to justice easier for everyone.
baseurl: "/blogs" # the subpath of your site, e.g. /blog
url: "https://blogs.laschool.online/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: LaTecSo
  links:
    - https://twitter.com/latecso
    - https://www.facebook.com/latecso
    - https://www.linkedin.com/in/latecso
    - https://github.com/latecso

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  LaTecSo: Bridging the gap between Law &amp; Technology in modern days 

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: hello@latecso.in # email for form submission

twitter_username: latecso # replace with your_twitter_username or comment to remove link from footer
github_username:  latecso # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
